services:
  web:
    build:
      context: .
      dockerfile: ./config/web.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web/src:/app/apps/web/src
    restart: unless-stopped
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./config/api.Dockerfile
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
      - TZ=America/Los_Angeles
    volumes:
      - ./apps/api/src:/app/apps/api/src
    restart: unless-stopped
